'use client';

import { useState, useEffect, useRef } from 'react';
import { useRouter } from 'next/navigation';
import Image from 'next/image';
import { useToast } from '@/context/ToastContext';
import { uploadProfileImage, changeToBasicProfile } from '@/lib/api/storage';
import { updateNickname } from '@/lib/api/user';
import Button from '@/component/Button';
import InputField from '@/component/InputField';
import StepIndicator from '@/app/signup/_component/StepIndicator';
import TopAreaSub from '@/component/top_area/TopAreaSub';

const defaultNicknames = [
  '절약하는 수달',
  '배고픈 카피바라',
  '자린고비 바다표범',
];

function getRandomNickname() {
  return defaultNicknames[Math.floor(Math.random() * defaultNicknames.length)];
}

function getProfileImageUrl(imageUrl: string | null | undefined): string {
  if (!imageUrl) {
    return '/profile_1.png';
  }
  
  if (imageUrl.startsWith('basic/')) {
    const key = imageUrl.replace('basic/', '').replace('.jpg', '');
    return `/profile_${key}.png`;
  }
  
  // 업로드된 이미지인 경우
  const r2PublicUrl = process.env.NEXT_PUBLIC_R2_PUBLIC_URL;
  const bucketName = process.env.NEXT_PUBLIC_R2_BUCKET_NAME;
  if (r2PublicUrl && bucketName) {
    const key = imageUrl.split('?')[0]; // timestamp 제거
    return `${r2PublicUrl}/${bucketName}/${key}`;
  }
  
  return '/profile_1.png';
}

interface ProfileSetupContentProps {
  initialNickname: string | null;
  initialProfileImageUrl: string | null;
}

export default function ProfileSetupContent({
  initialNickname,
  initialProfileImageUrl,
}: ProfileSetupContentProps) {
  const router = useRouter();
  const { showToast } = useToast();
  const formRef = useRef<HTMLFormElement>(null);

  const [nickname, setNickname] = useState<string>('');
  const [nicknameError, setNicknameError] = useState('');
  const [profilePreview, setProfilePreview] = useState<string | null>(null);
  const [profileFile, setProfileFile] = useState<File | null>(null);
  const [profileLoading, setProfileLoading] = useState(false);
  const [autoGeneratedNickname, setAutoGeneratedNickname] = useState<string>('');
  const [autoGeneratedProfileNumber, setAutoGeneratedProfileNumber] = useState<1 | 2 | 3 | null>(null);
  const [hasExistingProfile, setHasExistingProfile] = useState(false);
  const isInitialized = useRef(false);

  // 서버에서 가져온 프로필 정보를 초기값으로 설정
  useEffect(() => {
    if (isInitialized.current) return;
    
    isInitialized.current = true;
    
    // 닉네임 설정
    if (initialNickname) {
      setNickname(initialNickname);
      setAutoGeneratedNickname(initialNickname);
    } else {
      // 닉네임이 없으면 랜덤 생성
      const randomNickname = getRandomNickname();
      setAutoGeneratedNickname(randomNickname);
      setNickname(randomNickname);
    }
    
    // 프로필 이미지 설정
    if (initialProfileImageUrl) {
      const profileUrl = getProfileImageUrl(initialProfileImageUrl);
      setProfilePreview(profileUrl);
      setHasExistingProfile(true);
      
      // 기본 프로필인 경우 번호 추출
      if (initialProfileImageUrl.startsWith('basic/')) {
        const key = initialProfileImageUrl.replace('basic/', '').replace('.jpg', '');
        const profileNum = parseInt(key, 10) as 1 | 2 | 3;
        if (profileNum >= 1 && profileNum <= 3) {
          setAutoGeneratedProfileNumber(profileNum);
        }
      }
    } else {
      // 프로필 이미지가 없으면 랜덤 생성
      const randomProfileNumber = (Math.floor(Math.random() * 3) + 1) as 1 | 2 | 3;
      setAutoGeneratedProfileNumber(randomProfileNumber);
      setProfilePreview(`/profile_${randomProfileNumber}.png`);
      setHasExistingProfile(false);
    }
  }, [initialNickname, initialProfileImageUrl]);

  const handleProfileFileChange = (file: File | null) => {
    setProfileFile(file);
    if (file) {
      setProfilePreview(URL.createObjectURL(file));
    }
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const finalNickname = nickname.trim();
    if (!finalNickname) {
      setNicknameError('닉네임을 입력해주세요.');
      return;
    }

    setProfileLoading(true);
    try {
      // 프로필 이미지 저장
      if (profileFile) {
        // 사용자가 직접 선택한 이미지가 있는 경우 업로드
        await uploadProfileImage(profileFile);
      } else if (autoGeneratedProfileNumber && !profileFile && !hasExistingProfile) {
        // 기존 프로필이 없고 자동 생성된 프로필 이미지인 경우에만 기본 프로필로 설정
        await changeToBasicProfile(autoGeneratedProfileNumber);
      }
      // 기존 프로필이 있고 사용자가 새 파일을 선택하지 않은 경우는 아무것도 하지 않음 (기존 프로필 유지)

      // 닉네임 저장 (항상 저장)
      await updateNickname(finalNickname);
      // showToast('프로필 정보가 저장되었습니다.');
      // 프로필 설정 완료 후 권한 허용 페이지로 이동 (replace로 깜박임 방지, 로딩 상태 유지)
      router.replace('/signup/permissions');
    } catch (err: any) {
      setProfileLoading(false);
      const message = err?.message ?? '프로필 저장에 실패했습니다.';
      setNicknameError(message);
      // showToast(message);
    }
  };

  const handleBack = () => {
    router.push('/');
  };

  return (
    <div className="flex flex-col items-center min-h-screen w-full bg-white">
      <div className="w-full flex flex-col">
        <TopAreaSub onBack={handleBack} />
        <div className="flex flex-col min-h-screen pb-[calc(5rem+2rem)]">
          <div className="mt-[1rem] pt-[1.7rem] px-[2rem] pb-[1.6rem]">
            <StepIndicator current={3} />
          </div>
          <div className="pt-[1.4rem] px-[2rem] pb-[3.2rem]">
            <h1 className="text-headline-1 font-bold text-black">프로필과 닉네임을 설정해주세요</h1>
          </div>
          <div className="px-[2rem]">
            <form ref={formRef} onSubmit={handleSubmit} noValidate className="flex flex-col gap-[2.2rem]">
              <div className="flex flex-col items-center gap-3">
                <div className="relative">
                  <div className="w-[13.2rem] h-[13.2rem] rounded-[3.8rem] bg-[#EEF2F7] flex items-center justify-center overflow-hidden">
                    {profilePreview ? (
                      // eslint-disable-next-line @next/next/no-img-element
                      <img src={profilePreview} alt="profile preview" className="w-[13.2rem] h-[13.2rem] object-cover" />
                    ) : (
                      <span className="text-sm text-[#6B7280]">디폴트 이미지</span>
                    )}
                  </div>
                  <label className="absolute bottom-[-5px] right-[-11px] w-[3.6rem] h-[3.6rem] rounded-full bg-[#424242] text-white flex items-center justify-center cursor-pointer shadow-md hover:bg-[#616161] transition-colors">
                    <Image
                      src="/icons/icon-modify-36.svg"
                      alt="프로필 수정"
                      width={36}
                      height={36}
                    />
                    <input
                      type="file"
                      accept="image/*"
                      className="hidden"
                      onChange={(event) => {
                        const file = event.target.files?.[0];
                        if (file) {
                          handleProfileFileChange(file);
                        }
                      }}
                    />
                  </label>
                </div>
              </div>

              <InputField
                label="닉네임"
                name="nickname"
                placeholder="닉네임을 입력해주세요"
                value={nickname}
                description={nicknameError || '* 앞으로 보여질 닉네임이에요.'}
                descriptionType={nicknameError ? 'error' : 'default'}
                onChange={(e) => {
                  setNickname(e.target.value);
                  setNicknameError('');
                }}
                required
              />
            </form>
          </div>

          {/* 하단 고정 버튼 */}
          <div className="fixed bottom-0 left-0 right-0 p-5 bg-white md:left-1/2 md:right-auto md:w-[600px] md:-translate-x-1/2">
            <Button
              type="button"
              variant="default"
              disabled={profileLoading}
              onClick={() => {
                if (formRef.current) {
                  const event = new Event('submit', { cancelable: true, bubbles: true });
                  formRef.current.dispatchEvent(event);
                }
              }}
              className="w-full"
            >
              {profileLoading ? '저장 중...' : '다음'}
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}

